spring.application.name=Aniket
server.port=${SERVER_PORT:8080}
# Database Configuration (Uses Env Vars for Prod, defaults to Local)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/AniketDb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
# Specify the PostgreSQL driver
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA & Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Spring Profiles
spring.profiles.active=${SPRING_PROFILE:}
# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khangaraniket365@gmail.com
spring.mail.password=irxahspydqveqeqn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# MongoDb
# For local:
spring.data.mongodb.uri=mongodb://localhost:27017/aniket